const translations = {
  es: {
    airQualityMonitor: 'Monitor de Calidad del Aire',
    pollutants: 'Contaminantes',
    todayAQITrend: 'Tendencia ICA Hoy',
    weeklyAQITrend: 'Tendencia Semanal del ICA',
    monthlyAQITrend: 'Tendencia Mensual del ICA',
    alerts: 'Alertas',
    alertSettings: 'Configuración de Alertas',
    enableAlerts: 'Activar Alertas',
    aqiThreshold: 'Umbral de ICA',
    recentAlerts: 'Alertas Recientes',
    settings: 'Ajustes',
    generalSettings: 'Ajustes Generales',
    enableCloudSync: 'Activar Sincronización en la Nube',
    sensorInterval: 'Intervalo del Sensor (minutos)',
    accountSettings: 'Ajustes de la Cuenta',
    username: 'Nombre de Usuario',
    password: 'Contraseña',
    language: 'Idioma',
    spanish: 'Español',
    english: 'Inglés',
    saveSettings: 'Guardar Ajustes',
    home: 'Inicio',
    history: 'Historial',
    aiAdvice: 'Consejo de IA',
  },
  en: {
    airQualityMonitor: 'Air Quality Monitor',
    pollutants: 'Pollutants',
    todayAQITrend: 'Today AQI Trend',
    weeklyAQITrend: 'Weekly AQI Trend',
    monthlyAQITrend: 'Monthly AQI Trend',
    alerts: 'Alerts',
    alertSettings: 'Alert Settings',
    enableAlerts: 'Enable Alerts',
    aqiThreshold: 'AQI Threshold',
    recentAlerts: 'Recent Alerts',
    settings: 'Settings',
    generalSettings: 'General Settings',
    enableCloudSync: 'Enable Cloud Sync',
    sensorInterval: 'Sensor Interval (minutes)',
    accountSettings: 'Account Settings',
    username: 'Username',
    password: 'Password',
    language: 'Language',
    spanish: 'Spanish',
    english: 'English',
    saveSettings: 'Save Settings',
    home: 'Home',
    history: 'History',
    aiAdvice: 'AI Advice',
  },
};


export const getTranslation = (language, key) => {
  return translations[language]?.[key] || key
}
